# Generated by Django 5.0.6 on 2024-09-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_pictures_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(blank=True, default='images/placeholder.jpeg', upload_to='images'),
        ),
    ]
